### Sensor Save data
POST http://localhost:5001/sensors/api/savedata HTTP/1.1
content-type: application/json

{
            "sensor_id": "TEKO_LU_5.3",
            "sensor_secret": "PW12345w!",
            "co2": 401,
            "temp": 26.937,
            "hum": 40,
            "timestamp": "27.06.2020 00:00:03"
}




### Sensor Save data
POST https://as.puchtuning.synology.me/sensors/api/savedata HTTP/1.1
content-type: application/json

{
"sensor_id": "PARU_HOME",
"sensor_secret": "PW12345w!",
  "data": [
    {
      "co2": 426,
      "temp": 25,
      "hum": 40,
      "timestamp": "13.01.2021 23:00:00"
    },
    {
      "co2": 4430,
      "temp": 25,
      "hum": 41,
      "timestamp": "13.01.2021 23:01:00"
    }]
}